services:
  - type: web
    name: eglise-contributions-v4
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_SECRET
        generateValue: true
      - key: CINETPAY_APIKEY
        sync: false
      - key: CINETPAY_SITE_ID
        sync: false
      - key: CINETPAY_SECRET_KEY
        sync: false
      - key: PUBLIC_BASE_URL
        sync: false
